### ISSUE TITLE
Dependency Convergence

### ISSUE THREAD

**Issue by franciscodominguez** [serenity-bdd/serenity-demos#1] opened 2015-03-02 23:11 UTC
I was using the jbehave-webtests maven project as a starting point. It works great except there seems to be a dependency convergence with the libs that are being used. Also needed to move back to 
```
<serenity.version>1.0.33</serenity.version>
    <serenity.maven.version>1.0.33</serenity.maven.version>
    <serenity.jbehave.version>1.0.17</serenity.jbehave.version>
```
since 1.0.34 is not downloadable.

Configure the following in your pom.xml:
```
<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>1.3</version>
          <executions>
            <execution>
              <id>verify</id>
              <phase>validate</phase>
              <goals>
                <goal>enforce</goal>
              </goals>
              <inherited>true</inherited>
            </execution>
          </executions>
          <configuration>
            <failFast>true</failFast>
            <rules>
              <DependencyConvergence></DependencyConvergence>
              <requireReleaseDeps>
                <onlyWhenRelease>true</onlyWhenRelease>
              </requireReleaseDeps>
              <requireJavaVersion>
                <version>${java.version}</version>
              </requireJavaVersion>
            </rules>
          </configuration>
        </plugin>
```
you will see the problems. It seems pretty straight forward to fix it but here is the output 

[ERROR] Failed while enforcing releasability the error(s) are [
[ERROR] Dependency convergence error for net.serenity-bdd:core:1.0.31 paths to dependency are:
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:serenity-jbehave:1.0.17
[ERROR] +-net.serenity-bdd:core:1.0.34
[ERROR] ,
[ERROR] Dependency convergence error for com.thoughtworks.xstream:xstream:1.4.1 paths to dependency are:
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-com.thoughtworks.xstream:xstream:1.4.1
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:serenity-jbehave:1.0.17
[ERROR] +-com.thoughtworks.xstream:xstream:1.4.5
[ERROR] ,
[ERROR] Dependency convergence error for cglib:cglib:2.2.2 paths to dependency are:
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-cglib:cglib:2.2.2
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-io.appium:java-client:2.1.0
[ERROR] +-cglib:cglib:3.1
[ERROR] ,
[ERROR] Dependency convergence error for com.google.code.gson:gson:2.3.1 paths to dependency are:
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-com.google.code.gson:gson:2.3.1
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-io.appium:java-client:2.1.0
[ERROR] +-com.google.code.gson:gson:2.2.4
[ERROR] ,
[ERROR] Dependency convergence error for org.seleniumhq.selenium:selenium-java:2.44.0 paths to dependency are:
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-org.seleniumhq.selenium:selenium-server:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-java:2.44.0
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-io.appium:java-client:2.1.0
[ERROR] +-org.seleniumhq.selenium:selenium-java:2.43.1
[ERROR] ,
[ERROR] Dependency convergence error for commons-logging:commons-logging:1.1.3 paths to dependency are:
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-commons-logging:commons-logging:1.1.3
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-net.serenity-bdd:serenity-report-resources:1.0.31
[ERROR] +-commons-logging:commons-logging:1.1.3
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:serenity-jbehave:1.0.17
[ERROR] +-commons-logging:commons-logging:1.2
[ERROR] ,
[ERROR] Dependency convergence error for org.slf4j:slf4j-api:1.7.5 paths to dependency are:
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-org.slf4j:slf4j-api:1.7.5
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-net.serenity-bdd:serenity-report-resources:1.0.31
[ERROR] +-org.slf4j:slf4j-api:1.7.5
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-org.slf4j:slf4j-simple:1.7.7
[ERROR] +-org.slf4j:slf4j-api:1.7.7
[ERROR] ,
[ERROR] Dependency convergence error for com.google.guava:guava:18.0 paths to dependency are:
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-com.google.guava:guava:18.0
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-net.serenity-bdd:serenity-report-resources:1.0.31
[ERROR] +-com.google.guava:guava:18.0
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-org.seleniumhq.selenium:selenium-server:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-java:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-chrome-driver:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-remote-driver:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-api:2.44.0
[ERROR] +-com.google.guava:guava:18.0
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-org.seleniumhq.selenium:selenium-server:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-java:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-chrome-driver:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-remote-driver:2.44.0
[ERROR] +-com.google.guava:guava:18.0
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-io.appium:java-client:2.1.0
[ERROR] +-com.google.guava:guava:17.0
[ERROR] ,
[ERROR] Dependency convergence error for org.apache.httpcomponents:httpclient:4.3.4 paths to dependency are:
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-org.seleniumhq.selenium:selenium-server:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-java:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-chrome-driver:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-remote-driver:2.44.0
[ERROR] +-org.apache.httpcomponents:httpclient:4.3.4
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-org.seleniumhq.selenium:selenium-server:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-java:2.44.0
[ERROR] +-org.seleniumhq.selenium:selenium-htmlunit-driver:2.44.0
[ERROR] +-org.apache.httpcomponents:httpclient:4.3.4
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-io.appium:java-client:2.1.0
[ERROR] +-org.apache.httpcomponents:httpclient:4.3.3
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-net.sourceforge.htmlunit:htmlunit:2.15
[ERROR] +-org.apache.httpcomponents:httpclient:4.3.3
[ERROR] and
[ERROR] +-net.serenitybdd.showcase:serenity-jbehave-showcase:0.0.1-SNAPSHOT
[ERROR] +-net.serenity-bdd:core:1.0.31
[ERROR] +-net.sourceforge.htmlunit:htmlunit:2.15
[ERROR] +-org.apache.httpcomponents:httpmime:4.3.3
[ERROR] +-org.apache.httpcomponents:httpclient:4.3.3
[ERROR] ]

**Comment by jeffjensen** [comment] 2015-03-03 04:09
Yes, we're also having this difficulty (prevents us from upgrading from 1.0.27!).

Please also see/contribute to issues in core: [26] (https://github.com/serenity-bdd/serenity-core/issues/26) [16] (https://github.com/serenity-bdd/serenity-core/issues/16) [18] (https://github.com/serenity-bdd/serenity-core/issues/18).

**Comment by wakaleo** [comment] 2015-03-03 05:04
Duplicate of #16

**Closed by wakaleo** 2015-03-03 05:04 UTC
